### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by owikle** [uidaholib/main-web-redesign_draft#300]
@dcnb and @evanwill - Passing along a folder where we’ve been recording progress and problems with the website: https://drive.google.com/open?id=1NTIBOM0k35Vn7QgKjK3EbGbxg3u2F3LK

Jylisa and I have made it through all of the pages now, double-checking page layouts, links, phone numbers, names, etc. You can find remaining problems here: https://docs.google.com/spreadsheets/d/1YfBYW0g12v-_bgvRN9o8TwQSp_L__sEuxyHYISh_RXw/edit?usp=sharing. I’m currently going back through this spreadsheet to fix as many of these as I can. 

Cindy’s still in the process of getting us access to some new material for the carousel on the front page. Once she does, I’ll work on adding it.

Safe travels, and see you soon!

**Comment by evanwill** [comment]
I don't have edit access to the spreadsheet, so can't comment, but I think I have fixed or started to fix things I am tagged in. 

- `/Services/Copyright/Copyright Guide` : working on it, see issue #325 
- `/Services/Instruction Services` : issue with Hours and other stuff-- this was because the `<iframe>` element was left unclosed, so it messed up all the code below that point in the page.
- `/Services/Workshops` : page seems fine to me? the calendar links out to LibCal which is correct.
- `/Special Collections/` : breadcrumbs (#325),  search page is a PHP page that will work on the real server
-

**Comment by owikle** [comment]
Thanks, @evanwill. Sorry about the spreadsheet, you should have access now.

**Comment by evanwill** [comment]
Thanks @owikle, 
I added the gdocs links to the README for reference, so closing this issue now.
