### ISSUE TITLE
Book a Room Images

### ISSUE THREAD

**Issue by dcnb** [uidaholib/main-web-redesign_draft#306]
We need them for the three rooms listed

**Comment by owikle** [comment]
I found some in the photo gallery and just asked Cindy to download them for us. I'll add them to the site when she does.

**Comment by evanwill** [comment]
@dcnb why did you remove the 3d printers? Is there a link anywhere else to book the printers?

**Comment by dcnb** [comment]
I thought they were filler because of language used. Are you back?

**Comment by evanwill** [comment]
I thought Kevin was going to supply some descriptions--he wanted the difference between the two printers to be explained before people go to the booking page, since it isn't very obvious on LibCal. 

(not back. my new car is in the shop. :cry: don't want to talk about it. but should be back for next week)

**Comment by dcnb** [comment]
Getting descriptions from Kevin tomorrow. Probably should just combine the printers into one thing and give some info on difference in card
